# Generated by Django 4.0.6 on 2022-07-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='categorys',
            field=models.ManyToManyField(to='main_app.category'),
        ),
    ]
