# Generated by Django 4.0.6 on 2022-07-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_observation_date_remove_observation_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cat',
            new_name='observation',
        ),
    ]
